### ISSUE TITLE
Cache Eviction

### ISSUE THREAD

**Issue by charlessolar** [surgeforward/Surge-SlickGrid-Extensions#4]
I started using your extensions recently thanks to the nice and easy Nuget package.  However I was disappointed to find out you do not handle cache eviction with the JSONDataSource..
Kind of makes searching and sorting worthless since the old data will never be retrieved and you are left with artifacts.  A fact which your search demo cleverly hides.
I wanted to use sorting and searching in my grid, so I modified some code - here's what I did to refreshData()

```
refreshData: function () {
        var data = this._data;
        for (var key in data) {
            delete data[key];
        }

        vp = this._grid.getViewport();
        this.loadData(vp.top, vp.bottom);
    },
```

Thanks for the easy to use datasource :)

**Comment by togakangaroo** [comment]
Thanks @redcomet we will review this and might incorporate it into the widget.
